development: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  password: "12345"
  pool: 5
  timeout: 5000
  database: kob_portfolio_development

test:
  <<: *default
  database: kob_portfolio_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: kob_portfolio_production

